import {test,expect} from '@playwright/test';
test('拟合实时计算、手动参数、传播绑定与保存恢复',async({page})=>{
 test.setTimeout(60000);await page.goto('/');
 await page.locator('.dataset-tabs').getByRole('button',{name:'伏安法测电阻'}).click();
 await page.getByRole('button',{name:'数据预览',exact:true}).click();
 await page.getByRole('checkbox',{name:'曲线拟合',exact:true}).check();
 await expect(page.locator('.fit-metrics')).toContainText('拟合结果',{timeout:30000});
 await expect(page.locator('.fitted-curve')).toHaveCount(1);
 await expect(page.getByLabel('参数 a 值',{exact:true})).toHaveValue(/^9\.99/);
 await expect(page.getByLabel('拟合权重')).toHaveCount(0);
 await expect(page.getByLabel('拟合横轴下限')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'用拟合值更新初值'})).toHaveCount(0);
 await page.screenshot({path:'artifacts/fitting.png',fullPage:true});
 await page.getByLabel('参数模式').selectOption('manual');await page.getByLabel('参数 a 值',{exact:true}).fill('5');
 await expect(page.locator('.fit-metrics')).toContainText('手动曲线');
 const before=await page.locator('.fitted-curve').getAttribute('points');await page.getByLabel('参数 a 值',{exact:true}).fill('8');
 await expect.poll(()=>page.locator('.fitted-curve').getAttribute('points')).not.toBe(before);
 await page.getByLabel('参数模式').selectOption('auto');await expect(page.locator('.fit-metrics')).toContainText('拟合结果');
 await page.locator('.dataset-tabs').getByRole('button',{name:'长度的重复测量'}).click();
 await page.getByRole('button',{name:'科学计算',exact:true}).click();
 const source=page.getByLabel('变量 1 来源');const value=await source.locator('option').filter({hasText:'拟合参数 a'}).getAttribute('value');await source.selectOption(value!);
 await expect(page.getByLabel('科学计算结果')).toContainText('9.99');
 await page.getByRole('button',{name:'添加输入变量',exact:false}).click();
 const source2=page.getByLabel('变量 2 来源');const value2=await source2.locator('option').filter({hasText:'拟合参数 b'}).getAttribute('value');await source2.selectOption(value2!);
 await page.getByLabel('传播公式').fill('x*3+x2');await expect(page.getByLabel('科学计算结果')).toContainText('30.');
 await expect(page.getByRole('table',{name:'不确定度预算'})).toHaveCount(0);
 await page.screenshot({path:'artifacts/propagation.png',fullPage:true});
 await page.reload();await page.getByRole('button',{name:'科学计算',exact:true}).click();await expect(page.getByLabel('传播公式')).toHaveValue('x*3+x2');await expect(page.getByLabel('科学计算结果')).toContainText('30.');
 await page.locator('.dataset-tabs').getByRole('button',{name:'伏安法测电阻'}).click();await page.getByRole('button',{name:'数据预览',exact:true}).click();await page.getByRole('checkbox',{name:'曲线拟合',exact:true}).uncheck();await page.locator('.dataset-tabs').getByRole('button',{name:'长度的重复测量'}).click();await page.getByRole('button',{name:'科学计算',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('需要自动拟合');await expect(page.getByLabel('科学计算结果')).toHaveCount(0);
});
test('传播实时公式、相关系数和非法输入清除结果',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'科学计算',exact:true}).click();
 await page.getByLabel('变量 1 估计值').fill('10');await page.getByLabel('变量 1 标准不确定度').fill('0.2');
 await page.getByRole('button',{name:'添加输入变量',exact:false}).click();await page.getByLabel('变量 2 估计值').fill('2');await page.getByLabel('变量 2 标准不确定度').fill('0.1');
 await page.getByLabel('传播公式').fill('x/x2');await expect(page.getByLabel('传播最佳估计值')).toHaveText('(5.0 ± 0.3)');
 await page.locator('.correlations summary').click();await page.getByLabel('相关系数 x x2').fill('0.5');
 await expect(page.getByRole('table',{name:'不确定度预算'})).toContainText('r = 0.5');
 await page.getByLabel('传播公式').fill('1/(x-x)');await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByLabel('传播最佳估计值')).toHaveCount(0);
});
