import { test, expect } from '@playwright/test';
test('编辑、粘贴、排除、恢复、撤销与本地恢复', async ({page}) => {
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'基础物理实验',exact:true})).toBeVisible();
  const cell=page.getByRole('textbox',{name:'第1行 直径'});
  await cell.fill('13.125'); await cell.press('Tab'); await expect(cell).toHaveValue('13.13');
  await cell.evaluate(el=>{ const data=new DataTransfer();data.setData('text/plain','13.125\n12.54');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true})); });
  await page.getByRole('button',{name:'排除第1行',exact:true}).click();
  await expect(page.locator('tbody tr.excluded')).toHaveCount(1);
  await page.getByRole('button',{name:'恢复第1行',exact:true}).click();
  await expect(page.locator('tbody tr.excluded')).toHaveCount(0);
  await page.getByTitle('撤销', {exact:true}).click();
  await expect(page.locator('tbody tr.excluded')).toHaveCount(1);
  await page.reload(); await expect(cell).toHaveValue('13.13'); await expect(page.locator('tbody tr.excluded')).toHaveCount(1);
});
test('导出项目后重新导入，完整恢复数值与设置', async ({page}) => {
  await page.goto('/');
  await page.getByLabel('测量仪器',{exact:true}).fill('校准卡尺'); await page.getByLabel('测量仪器',{exact:true}).press('Tab');
  await page.getByLabel('误差限 δ', {exact:false}).fill('0.02'); await page.getByLabel('误差限 δ', {exact:false}).press('Tab');
  const downloadPromise=page.waitForEvent('download'); await page.getByRole('button',{name:'保存项目',exact:true}).click();
  const download=await downloadPromise; const path=await download.path();
  await page.locator('input[type=file]').setInputFiles(path!);
  await expect(page.getByRole('heading',{name:'基础物理实验（导入副本）',exact:true})).toBeVisible();
  await expect(page.getByLabel('测量仪器',{exact:true})).toHaveValue('校准卡尺');
  await expect(page.getByLabel('误差限 δ', {exact:false})).toHaveValue('0.02');
  await expect(page.getByRole('textbox',{name:'第1行 直径'})).toHaveValue('12.52');
});
test('删除数据组、撤销和横轴显示', async ({page}) => {
  await page.goto('/');
  await page.getByRole('button',{name:'删除数据组',exact:true}).click();
  await page.getByRole('button',{name:'确认删除',exact:true}).click();
  await expect(page.locator('.dataset-tabs button.selected')).toHaveText('伏安法测电阻');
  await expect(page.locator('.dataset-tabs button')).toHaveCount(3);
  await page.getByTitle('撤销',{exact:true}).click();
  await expect(page.locator('.dataset-tabs button')).toHaveCount(4);
  await page.getByRole('button',{name:'数据预览',exact:true}).click();
  await expect(page.locator('.x-axis-label')).toHaveText('电压 / V');
  await expect(page.locator('.x-tick text').first()).toHaveText('0');
  await page.screenshot({path:'artifacts/plot.png',fullPage:true});
});
test('误差限与四种分布实时换算，变量之间独立', async ({page}) => {
  await page.goto('/');
  await page.locator('.dataset-tabs').getByRole('button',{name:'伏安法测电阻'}).click();
  const delta=page.getByLabel('误差限 δ',{exact:false});
  await delta.fill('6');await delta.press('Tab');
  const output=page.getByLabel('B 类标准不确定度',{exact:true});
  await expect(output).toContainText(String(6/Math.sqrt(3)));
  await page.getByLabel('分布',{exact:true}).selectOption('triangular');await expect(output).toContainText(String(6/Math.sqrt(6)));
  await page.getByLabel('分布',{exact:true}).selectOption('normal3');await expect(output).toHaveText('2 V');
  await page.getByLabel('分布',{exact:true}).selectOption('normal2');await expect(output).toHaveText('3 V');
  await page.getByRole('textbox',{name:'第1行 电流',exact:true}).focus();await expect(delta).toHaveValue('');await expect(output).toHaveText('—');
  await page.getByRole('textbox',{name:'第1行 电压',exact:true}).focus();await expect(delta).toHaveValue('6');
  await delta.fill('-1');await delta.press('Tab');await expect(delta).toHaveValue('6');
  await delta.fill('');await delta.press('Tab');await expect(output).toHaveText('—');
});
test('统计评定、异常值排除重算、参数恢复及成对数据保护', async ({page}) => {
  await page.goto('/');
  await page.getByRole('button',{name:'示例实验',exact:true}).click();
  await page.locator('.example-card').filter({hasText:'含疑似异常值的测量'}).click();
  await expect(page.locator('tbody tr.suspected')).toHaveCount(1);
  await page.getByLabel('误差限 δ',{exact:false}).fill('0.02');
  await page.getByLabel('误差限 δ',{exact:false}).press('Tab');
  await page.getByRole('button',{name:'统计评定',exact:true}).click();
  await expect(page.getByTestId('stat-mean')).toHaveText('20.053');
  await expect(page.getByTestId('stat-combined')).not.toHaveText('—');
  await expect(page.getByText('疑似异常：第 7 行',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'排除此点',exact:true}).click();
  await expect(page.getByText('未检出异常值',{exact:true})).toBeVisible();
  await expect(page.getByTestId('stat-mean')).toHaveText('20.02');
  await page.getByLabel('显著性水平',{exact:true}).selectOption('0.01');
  await page.getByText('分布直方图',{exact:true}).click();
  await page.screenshot({path:'artifacts/statistics.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.reload();await page.getByRole('button',{name:'统计评定',exact:true}).click();
  await expect(page.getByLabel('显著性水平',{exact:true})).toHaveValue('0.01');
  await expect(page.getByTestId('stat-mean')).toHaveText('20.02');
  await page.locator('.dataset-tabs').getByRole('button',{name:'伏安法测电阻'}).click();
  await expect(page.getByRole('button',{name:'统计评定',exact:true})).toHaveCount(0);
});
test('截图与无错误渲染', async ({page}) => {
  const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/'); await page.screenshot({path:'artifacts/workbench.png',fullPage:true});await page.locator('.dataset-tabs').getByRole('button',{name:'伏安法测电阻'}).click();
  await page.getByRole('button',{name:'数据预览',exact:true}).click(); await expect(page.getByRole('img',{name:'原始测量数据预览'})).toBeVisible();
  await page.getByRole('button',{name:'示例实验',exact:true}).click(); await expect(page.locator('.example-grid')).toBeVisible();
  await page.setViewportSize({width:390,height:844}); await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy(); expect(errors).toEqual([]);
});
test('横向编辑粘贴、方向恢复、统计数据与最佳估计值', async ({page}) => {
  await page.goto('/');
  await page.getByRole('button',{name:'横向表格',exact:true}).click();
  await expect(page.locator('.horizontal-table')).toBeVisible();
  const cell=page.getByRole('textbox',{name:'第1行 直径',exact:true});
  await cell.evaluate(el=>{const data=new DataTransfer();data.setData('text/plain','12.52\t12.54');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});
  await expect(page.getByRole('textbox',{name:'第2行 直径',exact:true})).toHaveValue('12.54');
  await page.getByLabel('误差限 δ',{exact:false}).fill('0.02');await page.getByLabel('误差限 δ',{exact:false}).press('Tab');
  await page.screenshot({path:'artifacts/horizontal.png',fullPage:true});
  await page.getByRole('button',{name:'统计评定',exact:true}).click();
  await expect(page.getByRole('table',{name:'测量数据表'})).toBeVisible();
  await expect(page.getByLabel('最佳估计值',{exact:true})).toHaveText('(12.53 ± 0.02) mm');
  await expect(page.locator('.horizontal-table .data-number').first()).toHaveText('12.52');
  await page.screenshot({path:'artifacts/estimate.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.reload();await expect(page.getByRole('button',{name:'横向表格',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'纵向表格',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'第1行 直径',exact:true})).toHaveValue('12.52');
});

test('项目删除后不保留副本，空项目状态跨刷新保留',async({page})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'删除项目 基础物理实验',exact:true}).click();
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await expect(page.getByRole('heading',{name:'基础物理实验',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'删除项目 基础物理实验',exact:true}).click();
  await page.getByRole('button',{name:'确认删除',exact:true}).click();
  await expect(page.getByRole('heading',{name:'暂无项目',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'保存项目',exact:true})).toBeDisabled();
  await page.reload();await expect(page.getByRole('heading',{name:'暂无项目',exact:true})).toBeVisible();
  for(const name of ['已删除项目','操作记录','使用指南'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('physical-lab.workspace.v1')!));expect(saved.projects).toEqual([]);expect(saved.deletedProjects).toBeUndefined();
});
test('连续测量序号与修约选项保存',async({page})=>{
  await page.goto('/');
  await expect(page.locator('.measure-table tbody .index-col')).toHaveText(Array.from({length:10},(_,i)=>String(i+1)));
  await page.locator('.dataset-tabs').getByRole('button',{name:'伏安法测电阻'}).click();
  await page.getByRole('button',{name:'数据预览',exact:true}).click();
  await page.getByLabel('自变量 · 横轴',{exact:true}).selectOption('sequence');
  await expect(page.locator('.x-tick text')).toHaveText(Array.from({length:10},(_,i)=>String(i+1)));
  await page.locator('.dataset-tabs').getByRole('button',{name:'长度的重复测量'}).click();
  await page.getByRole('button',{name:'数据表格',exact:true}).click();
  await page.getByLabel('误差限 δ',{exact:false}).fill('0.02');await page.getByLabel('误差限 δ',{exact:false}).press('Tab');
  await page.getByRole('button',{name:'统计评定',exact:true}).click();
  await expect(page.getByLabel('最佳估计值',{exact:true})).toHaveText('(12.53 ± 0.02) mm');
  await page.getByLabel('不确定度有效位数',{exact:true}).selectOption('2');
  await expect(page.getByLabel('最佳估计值',{exact:true})).toHaveText('(12.526 ± 0.014) mm');
  await page.reload();await page.getByRole('button',{name:'统计评定',exact:true}).click();
  await expect(page.getByLabel('不确定度有效位数',{exact:true})).toHaveValue('2');
});
test('设置栏仅表格显示、统计页顺序及分量不修约',async({page})=>{
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'数据设置',exact:true})).toBeVisible();
  await page.getByLabel('误差限 δ',{exact:false}).fill('0.02');await page.getByLabel('误差限 δ',{exact:false}).press('Tab');
  await page.getByRole('button',{name:'统计评定',exact:true}).click();
  await expect(page.getByRole('heading',{name:'数据设置',exact:true})).toHaveCount(0);
  const ua=await page.getByTestId('stat-ua').textContent(),ub=await page.getByTestId('stat-ub').textContent();
  expect(Number(ub)).toBe(0.02/Math.sqrt(3));expect(Number(ua)).toBeCloseTo(0.006,12);
  await page.getByLabel('不确定度有效位数',{exact:true}).selectOption('2');
  await expect(page.getByTestId('stat-ua')).toHaveText(ua!);await expect(page.getByTestId('stat-ub')).toHaveText(ub!);
  const order=await page.evaluate(()=>{const data=document.querySelector('.measurement-grid')!,grubbs=document.querySelector('.grubbs-section')!,stats=document.querySelector('.statistics-table')!;return Boolean(data.compareDocumentPosition(grubbs)&Node.DOCUMENT_POSITION_FOLLOWING)&&Boolean(grubbs.compareDocumentPosition(stats)&Node.DOCUMENT_POSITION_FOLLOWING);});
  expect(order).toBeTruthy();await page.screenshot({path:'artifacts/statistics-layout.png',fullPage:true});
  await page.locator('.dataset-tabs').getByRole('button',{name:'伏安法测电阻'}).click();
  await page.getByRole('button',{name:'数据预览',exact:true}).click();await expect(page.locator('.inspector')).toHaveCount(0);
  await page.getByRole('button',{name:'数据表格',exact:true}).click();await expect(page.locator('.inspector')).toBeVisible();
});
test('列出全部变量、切换和编辑，以及坐标轴保存恢复',async({page})=>{
  await page.goto('/');await page.locator('.dataset-tabs').getByRole('button',{name:'伏安法测电阻'}).click();
  await expect(page.locator('.variables-list .variable-box')).toHaveCount(2);
  await page.getByRole('button',{name:'选择变量 电流',exact:true}).click();
  await expect(page.getByRole('button',{name:'选择变量 电流',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'编辑变量 电流',exact:true}).click();await expect(page.getByLabel('名称',{exact:true})).toHaveValue('电流');await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.getByRole('button',{name:'数据预览',exact:true}).click();
  await page.getByLabel('自变量 · 横轴',{exact:true}).selectOption({label:'电流 · I / mA'});
  await page.getByLabel('因变量 · 纵轴',{exact:true}).selectOption({label:'电压 · U / V'});
  await expect(page.locator('.x-axis-label')).toHaveText('电流 / mA');await expect(page.locator('.plot-label')).toContainText('电压 / V');
  await page.screenshot({path:'artifacts/axis-selection.png',fullPage:true});
  await page.reload();await page.getByRole('button',{name:'数据预览',exact:true}).click();
  await expect(page.locator('.x-axis-label')).toHaveText('电流 / mA');
  await page.getByLabel('自变量 · 横轴',{exact:true}).selectOption('sequence');await expect(page.locator('.x-axis-label')).toHaveText('测量序号');
});