<script setup lang="ts">
import MathLabel from './MathLabel.vue';
import { computed, ref } from 'vue';
import { ChevronDown, ListFilter, Plus, Trash2, Undo2 } from 'lucide-vue-next';
import type { Dataset } from './model';
const props=withDefaults(defineProps<{dataset:Dataset;columnIndex:number;showExcluded?:boolean;suspectedRow?:string;readonly?:boolean}>(),{showExcluded:true,readonly:false});
const emit=defineEmits<{column:[number];layout:['vertical'|'horizontal'];cell:[Event,number,number];paste:[ClipboardEvent,number,number];exclude:[string];delete:[string];add:[]}>();
const rows=computed(()=>props.dataset.rows.map((r,index)=>({...r,index})).filter(r=>props.showExcluded || !r.excluded));
const grid=ref<HTMLElement>();
const hoveredMeasurement=ref<string|null>(null);
function navigate(event:KeyboardEvent,ri:number,ci:number){
  if(event.isComposing || event.altKey || event.ctrlKey || event.metaKey || event.shiftKey)return;
  const directions:Record<string,[number,number]>={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};
  const direction=directions[event.key];if(!direction)return;
  event.preventDefault();
  const horizontal=props.dataset.table_layout==='horizontal';
  const row=rows.value.findIndex(r=>r.index===ri)+(horizontal?direction[1]:direction[0]);
  const col=ci+(horizontal?direction[0]:direction[1]);
  if(row<0 || row>=rows.value.length || col<0 || col>=props.dataset.columns.length)return;
  const target=grid.value?.querySelector<HTMLInputElement>(`input[data-row="${rows.value[row]!.index}"][data-column="${col}"]`);
  target?.focus();target?.select();
}
const format=(v:number|null,precision:number)=>v===null?'—':v.toFixed(precision);
const title=(r:typeof rows.value[number])=>r.id===props.suspectedRow?'Grubbs 疑似异常值':r.reason;
</script>
<template>
  <div ref="grid" class="measurement-grid" :class="{'read-only':readonly}">
    <div class="grid-heading"><span v-if="readonly">测量数据</span><div class="layout-switch" role="group" aria-label="表格方向"><button :aria-pressed="dataset.table_layout==='vertical'" @click="emit('layout','vertical')">纵向表格</button><button :aria-pressed="dataset.table_layout==='horizontal'" @click="emit('layout','horizontal')">横向表格</button></div></div>
    <div class="grid-scroll">
      <table v-if="dataset.table_layout==='vertical'" class="measure-table" aria-label="测量数据表"><thead><tr><th class="index-col">序号</th><th v-for="(c,ci) in dataset.columns" :key="c.id" :class="{focused:ci===columnIndex}"><button @click="emit('column',ci)">{{c.name}} <i><MathLabel :text="c.display_symbol || c.symbol"/></i><span class="unit">{{c.unit ? '/ '+c.unit : ''}}</span><ChevronDown :size="13"/></button></th><th v-if="!readonly" class="row-actions"/></tr></thead><tbody><tr v-for="r in rows" :key="r.id" :class="{excluded:r.excluded,suspected:r.id===suspectedRow}" :title="title(r)"><td class="index-col">{{r.index+1}}</td><td v-for="(c,ci) in dataset.columns" :key="c.id" :class="{focused:ci===columnIndex}"><span v-if="readonly" class="data-number">{{format(r.values[ci]!,c.precision)}}</span><input v-else :data-row="r.index" :data-column="ci" @keydown="navigate($event,r.index,ci)" :aria-label="`第${r.index+1}行 ${c.name}`" inputmode="decimal" :value="r.values[ci]===null?'':format(r.values[ci]!,c.precision)" placeholder="—" @focus="emit('column',ci)" @change="emit('cell',$event,r.index,ci)" @paste="emit('paste',$event,r.index,ci)"/></td><td v-if="!readonly" class="row-actions"><button :aria-label="`${r.excluded?'恢复':'排除'}第${r.index+1}行`" :title="r.excluded?'恢复：'+r.reason:'排除数据'" :class="{'is-excluded':r.excluded}" @click="emit('exclude',r.id)"><component :is="r.excluded?Undo2:ListFilter" :size="14"/></button><button :aria-label="`删除第${r.index+1}行`" title="删除行" @click="emit('delete',r.id)"><Trash2 :size="13"/></button></td></tr></tbody></table>
      <table v-else class="measure-table horizontal-table" @mouseleave="hoveredMeasurement=null" aria-label="测量数据表"><thead><tr><th class="variable-header">序号</th><th v-for="r in rows" :key="r.id" @mouseenter="hoveredMeasurement=r.id" :class="{excluded:r.excluded,suspected:r.id===suspectedRow}" :title="title(r)"><div class="measurement-header"><span>{{r.index+1}}</span><span v-if="!readonly" class="horizontal-actions" :class="{revealed:hoveredMeasurement===r.id}"><button :aria-label="`${r.excluded?'恢复':'排除'}第${r.index+1}行`" :title="r.excluded?'恢复：'+r.reason:'排除数据'" @click="emit('exclude',r.id)"><component :is="r.excluded?Undo2:ListFilter" :size="12"/></button><button :aria-label="`删除第${r.index+1}行`" title="删除测量" @click="emit('delete',r.id)"><Trash2 :size="12"/></button></span></div></th></tr></thead><tbody><tr v-for="(c,ci) in dataset.columns" :key="c.id"><th class="variable-header" :class="{focused:ci===columnIndex}"><button @click="emit('column',ci)">{{c.name}} <i><MathLabel :text="c.display_symbol || c.symbol"/></i><span class="unit">{{c.unit ? '/ '+c.unit : ''}}</span></button></th><td v-for="r in rows" :key="r.id" @mouseenter="hoveredMeasurement=r.id" :class="{excluded:r.excluded,suspected:r.id===suspectedRow,focused:ci===columnIndex}" :title="title(r)"><span v-if="readonly" class="data-number">{{format(r.values[ci]!,c.precision)}}</span><input v-else :data-row="r.index" :data-column="ci" @keydown="navigate($event,r.index,ci)" :aria-label="`第${r.index+1}行 ${c.name}`" inputmode="decimal" :value="r.values[ci]===null?'':format(r.values[ci]!,c.precision)" placeholder="—" @focus="emit('column',ci)" @change="emit('cell',$event,r.index,ci)" @paste="emit('paste',$event,r.index,ci)"/></td></tr></tbody></table>
      <p v-if="!rows.length" class="empty-grid">暂无数据</p>
    </div>
    <button v-if="!readonly" class="add-row" @click="emit('add')"><Plus :size="14"/>{{dataset.table_layout==='horizontal'?'添加一次测量':'添加一行'}}</button>
  </div>
</template>
<style scoped>
.measure-table .index-col,.measurement-header>span:first-child{font-size:12px;color:#637f70;font-variant-numeric:tabular-nums}
.measurement-grid{padding:0 20px}.grid-heading{display:flex;align-items:center;justify-content:space-between;min-height:48px;font-size:12px;color:#708b7b}.layout-switch{display:flex;margin-left:auto;border:1px solid #e3ebe6;border-radius:5px;padding:2px}.layout-switch button{font-size:10px;padding:4px 9px;border-radius:3px;color:#8ca092}.layout-switch button[aria-pressed=true]{background:#eaf3ee;color:#407b62}.grid-scroll{overflow:auto;max-height:calc(100vh - 365px);scrollbar-width:thin}.measure-table{min-width:100%}.measure-table th{white-space:nowrap}.measure-table th button{gap:7px}.measure-table th button svg{margin-left:auto}.measure-table input{min-width:100px}.data-number{display:block;padding:10px 13px;font-family:Consolas,monospace;font-size:12px}.horizontal-table{width:max-content;border-collapse:separate;border-spacing:0}.horizontal-table th:not(.variable-header),.horizontal-table td{min-width:105px;width:105px}.horizontal-table input{width:105px}.variable-header{position:sticky;left:0;z-index:2;background:#f4f8f5;text-align:left;min-width:145px;padding:10px 12px;border-bottom:1px solid #e7ede8;font-size:11px;font-weight:400}.variable-header button{padding:0;font-size:11px}.horizontal-table thead .variable-header{z-index:3}.measurement-header{display:flex;align-items:center;justify-content:space-between;padding:0 10px;gap:8px}.horizontal-actions{display:flex;gap:5px;opacity:0;pointer-events:none}.horizontal-actions.revealed,.horizontal-actions:focus-within{opacity:1;pointer-events:auto}.horizontal-actions button{width:auto;padding:0;opacity:.45}.horizontal-actions button:hover,.horizontal-actions button:focus-visible{opacity:1}.excluded .data-number,td.excluded input{text-decoration:line-through;color:#aab4a7}.horizontal-table td.suspected,.horizontal-table th.suspected{background:#fbf6e9}.horizontal-table td.excluded,.horizontal-table th.excluded{background:#f6f6f1}.empty-grid{padding:20px;text-align:center;color:#97a798;font-size:12px}.read-only{padding:0;margin-bottom:20px}.read-only .grid-scroll{max-height:220px}.read-only .grid-heading{padding-top:0}.read-only th{position:sticky;top:0}.read-only .variable-header{left:0}.read-only .data-number{font-size:11px;padding:8px 13px}@media(max-width:760px){.measurement-grid{padding:0 12px}.read-only{padding:0}.grid-scroll{max-height:400px}.variable-header{min-width:125px}}
</style>
